name: Sync changes from release tag
on:
  release:
    types: [published, created, released]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - name: Override release branch with changes from release tag
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "team-devx+github-bot@konghq.com"
          git config --global user.name "team-devx"
          git reset --hard ${{ github.event.release.target_commitish }}
          git push --force-with-lease origin release
