name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - master
    - main
  workflow_dispatch: {}


jobs:
  semgrep:
    name: SAST
    runs-on: ubuntu-20.04
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: Kong/public-shared-actions/security-actions/semgrep@a18abf762d6e2444bcbfd20de70451ea1e3bc1b1
        with:
          additional_config: '--config p/rust'
