name: Sync Changes From Release Tag
on:
  release:
    types: published
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
          token: ${{ secrets.GHA_TEAM_DEVX_KONG_BOT_PAT }}
      - name: Override release branch with changes from release tag
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GHA_TEAM_DEVX_KONG_BOT_PAT }}
        run: |
          git config --global user.email "team-devx+github-bot@konghq.com"
          git config --global user.name "team-devx"
          git reset --hard ${{ github.event.release.tag_name }}
          git push --force-with-lease origin release
